In [1]:
import numpy as np

In [2]:
a3 = np.array([[[10,11,12],[13,14,15],[16,17,18]],
              [[19,20,21],[22,23,24],[25,26,27]],
             [[28,29,30],[31,32,33],[34,35,36]]])


In [3]:
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [4]:
a3[:,1,2]

array([15, 24, 33])

In [5]:
a3[:,2,2]

array([18, 27, 36])

In [6]:
a3[:,0,0]

array([10, 19, 28])

In [7]:
a3[:,0:2,0:2]

array([[[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]],

       [[28, 29],
        [31, 32]]])

In [8]:
a3[:,1:3,1:3]

array([[[14, 15],
        [17, 18]],

       [[23, 24],
        [26, 27]],

       [[32, 33],
        [35, 36]]])

In [9]:
a3[:,2,1]

array([17, 26, 35])

In [10]:
a3[:,0:3,0:3]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [11]:
a3[:,2:3,2:3]

array([[[18]],

       [[27]],

       [[36]]])

In [12]:
a3[:,1:2,1:2]

array([[[14]],

       [[23]],

       [[32]]])

In [13]:
a3[:,0:2,0:2]

array([[[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]],

       [[28, 29],
        [31, 32]]])

In [14]:
a3[:,1,2]

array([15, 24, 33])

In [15]:
a3[:,:,1]

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [16]:
a3[:,1:2,1:2]

array([[[14]],

       [[23]],

       [[32]]])

In [17]:
a3[:,1,1]

array([14, 23, 32])

In [18]:
a3[:,:0,0:2]

array([], shape=(3, 0, 2), dtype=int32)

In [19]:
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [20]:
a3[:,0,1]

array([11, 20, 29])

In [22]:
a3[:]

array([], shape=(3, 0, 0), dtype=int32)

In [23]:
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [25]:
a3[:,0:3,0:3]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [26]:
a3[:,2:3,2:3]


array([[[18]],

       [[27]],

       [[36]]])

In [27]:
a3[:,1:3,1:3]

array([[[14, 15],
        [17, 18]],

       [[23, 24],
        [26, 27]],

       [[32, 33],
        [35, 36]]])

In [28]:
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [30]:
a3[:,2,:]

array([[16, 17, 18],
       [25, 26, 27],
       [34, 35, 36]])

In [31]:
a3[:,:,1]

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

In [33]:
a3[:,1:2,1:2]

array([[[14]],

       [[23]],

       [[32]]])

In [34]:
a3[:,:,2]

array([[12, 15, 18],
       [21, 24, 27],
       [30, 33, 36]])

In [35]:
a3[:,:2,:]

array([[[10, 11, 12],
        [13, 14, 15]],

       [[19, 20, 21],
        [22, 23, 24]],

       [[28, 29, 30],
        [31, 32, 33]]])

In [37]:
a3[:,1:,:]

array([[[13, 14, 15],
        [16, 17, 18]],

       [[22, 23, 24],
        [25, 26, 27]],

       [[31, 32, 33],
        [34, 35, 36]]])

In [38]:
a3[:,:,1:]

array([[[11, 12],
        [14, 15],
        [17, 18]],

       [[20, 21],
        [23, 24],
        [26, 27]],

       [[29, 30],
        [32, 33],
        [35, 36]]])

In [41]:
a3[:,1:3,0:2]

array([[[13, 14],
        [16, 17]],

       [[22, 23],
        [25, 26]],

       [[31, 32],
        [34, 35]]])

In [42]:
a3[1,1:,0:2]

array([[22, 23],
       [25, 26]])

In [43]:
a3[2,1:,1:]

array([[32, 33],
       [35, 36]])

In [44]:
a3

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [45]:
a3[:,1:3,1:3]

array([[[14, 15],
        [17, 18]],

       [[23, 24],
        [26, 27]],

       [[32, 33],
        [35, 36]]])